# Generated by Django 5.0.1 on 2024-02-10 21:54

import ckeditor_uploader.fields
import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=main.models.user_dir_path)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank='True', null='true')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=999999999)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=999999999)),
                ('stock_status', models.CharField(choices=[('instock', 'in Stock'), ('outofstock', 'Out of Stock')], default='instock', max_length=10)),
                ('product_status', models.CharField(choices=[('inreview', 'in Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='inreview', max_length=100)),
                ('warranty_period', models.CharField(default='100', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('specifications', models.TextField(max_length=100)),
                ('digital', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='main.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='product-imgs')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='main.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_id', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=main.models.user_dir_path)),
                ('description', models.CharField(blank=True, default='Simply The best', max_length=100, null=True)),
                ('rating', models.CharField(default='100', max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('return_time', models.CharField(default='10', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('shipping_time', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('storefront_image', models.ImageField(upload_to=main.models.user_dir_path)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Retailers',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.retailer'),
        ),
    ]
