# Generated by Django 5.0.1 on 2024-02-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_category_id_alter_product_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
