# Generated by Django 5.0.1 on 2024-03-06 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_productreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=999999999)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('paid_status', models.BooleanField(default=False)),
                ('product_status', models.CharField(choices=[('inreview', 'in Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='published', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_status', models.CharField(choices=[('inreview', 'in Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='published', max_length=30)),
                ('item', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=999999999)),
                ('total', models.DecimalField(decimal_places=2, max_digits=999999999)),
                ('invoice_no', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
            ],
        ),
    ]
