# Generated by Django 5.0.1 on 2024-03-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart Orders'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='date_added',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='order_total_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='paid_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_status',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_status',
        ),
    ]
