# Generated by Django 5.0.1 on 2024-03-25 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_cartitem_invoice_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total_price', models.DecimalField(decimal_places=2, max_digits=999999999)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('shipping_address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('payment_method', models.BooleanField(choices=[('dbt', 'Direct Bank Transfer'), ('cod', 'Cash On Delivery')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart Orders',
            },
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
