# Generated by Django 5.0.1 on 2024-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_order_alter_cartitem_order_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('dbt', 'Direct Bank Transfer'), ('cod', 'Cash On Delivery')], default='dbt', max_length=200),
        ),
    ]
