# Generated by Django 5.0.1 on 2024-03-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_order_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
