# Generated by Django 5.0.1 on 2024-03-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='invoice_no',
        ),
    ]
